version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vuetify-image-input
    versions:
    - ">= 19.2.a, < 19.3"
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: vuetify
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: nuxt
    versions:
    - 2.15.2
    - 2.15.3
  - dependency-name: nuxt-start
    versions:
    - 2.15.2
    - 2.15.3
  - dependency-name: "@nuxtjs/axios"
    versions:
    - 5.13.0
    - 5.13.1
  - dependency-name: "@nuxtjs/pwa"
    versions:
    - 3.3.5
  - dependency-name: lint-staged
    versions:
    - 10.5.4
