kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build amd64
    image: plugins/docker
    settings:
      purge: true
      compress: true
      tags: test2,stable2
      repo: mrnaif/test-admin
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
