kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build amd64
    image: plugins/docker
    settings:
      repo: mrnaif/test-admin
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
---
kind: pipeline
type: docker
name: arm

platform:
  os: linux
  arch: arm

steps:
  - name: build arm
    image: plugins/docker
    settings:
      repo: mrnaif/test-admin
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build arm64
    image: plugins/docker
    settings:
      repo: mrnaif/test-admin
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      spec: .drone/docker-manifest.tmpl

depends_on:
  - amd64
  - arm
  - arm64
